[build]
    command = "npm run build" # or "vite build"
    publish = "dist"

    [functions]
    directory = "netlify/functions"

    [dev]
    command = "npm run dev" # or "vite"
    port = 3000
    targetPort = 3000